### ISSUE TITLE
Como começar?

### ISSUE THREAD

**Issue by RodrigoDornelles** [Franzininho/Franzininho-WIFI-dev-edition#3]
Estou procurando e não encontro, o Franzininho tem uma blibioteca padrão, core ou framework? se tem onde encontro o código fonte e documentação dela?

**Comment by FBSeletronica** [comment]
Rodrigo, 

Você encontra a documentação de todos os projetos aqui: https://franzininho.github.io/docs-franzininho-site/docs

Ainda está em construção.
